stages:
  prepare_data:
    cmd: python3 src-train/prepare_data.py
    deps:
      - prompts/system-prompt.md
      - prompts/prompt-template.md
      - data/raw
      - src-train/prepare_data.py
    outs:
      - data/dataset_train.jsonl
      - data/dataset_eval.jsonl

  prepare_data_dialogs:
    cmd: python3 src-train/prepare_data_dialogs.py
    deps:
      - prompts/system-prompt_dialogs.md
      - prompts/prompt-template_dialogs.md
      - prompts/prompt-template-dynamic-few-shots_dialogs_sample.md
      - data/raw_dialogs
      - src-train/prepare_data_dialogs.py
    outs:
      - data/dataset_train_dialogs.jsonl
      - data/dataset_eval_dialogs.jsonl
      - data/dataset_full_dialogs.jsonl
      - data/few_shots_dialogs_train_0.jsonl
      - data/few_shots_dialogs_train_1.jsonl
      - data/few_shots_dialogs_train_2.jsonl
      - data/few_shots_dialogs_train_3.jsonl
      - data/few_shots_dialogs_train_4.jsonl
      - data/few_shots_dialogs_train_5.jsonl
      - data/few_shots_dialogs_eval_0.jsonl
      - data/few_shots_dialogs_eval_1.jsonl
      - data/few_shots_dialogs_eval_2.jsonl
      - data/few_shots_dialogs_eval_3.jsonl
      - data/few_shots_dialogs_eval_4.jsonl
      - data/few_shots_dialogs_eval_5.jsonl
      - data/few_shots_dialogs_full_0.jsonl
      - data/few_shots_dialogs_full_1.jsonl
      - data/few_shots_dialogs_full_2.jsonl
      - data/few_shots_dialogs_full_3.jsonl
      - data/few_shots_dialogs_full_4.jsonl
      - data/few_shots_dialogs_full_5.jsonl

