stages:
  prepare_data:
    cmd: python3 src-train/prepare_data.py
    deps:
      - prompts/system-prompt.md
      - prompts/prompt-template.md
      - data/raw
      - src-train/prepare_data.py
    outs:
      - data/dataset_train.jsonl
      - data/dataset_train_sample.jsonl
      - data/dataset_eval.jsonl
